### PR TITLE
Remove obsolete python code (<3.6).

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Glandos** [comment]
I personally love f-strings. They are cleaner, and on top of that, more performant at runtime.

But are we sure than we can expect all our user base to have python >= 3.6?

**Comment by Natim** [comment]
> But are we sure than we can expect all our user base to have python >= 3.6?

Definitely yes. [Python 3.5 endoflife is September 2020](https://devguide.python.org/#status-of-python-branches) and people can still use a previous version in the meantime.

**Comment by Glandos** [comment]
And Python3.6 is available in CentOS7. OK, let's go.

**Comment by zorun** [comment]
As I already said in #421 and #475, I'm a bit sad about dropping support for Python 3.5 while both Python 3.5 and Debian stretch are still maintained (until September 2020 for Python 3.5, and until [June 2022](https://wiki.debian.org/LTS) for Debian stretch). But at this point, buster has been out for 9 months already so it's less annoying. I guess I'll just have to finally upgrade my server ;)
This will of course need to go in the upgrade notes for IHM 5.0.

@Natim btw, you seem to have missed a reference to python 3.5 in `docs/installation.rst`

**Comment by JocelynDelalande** [comment]
Ouch, I missed the conversation about it.

A bit sad also, because as yunohost is still on stretch, and it will stop ihatemoney_ynh from receiving ihm upgrades for a while for little actual gain (except dev ease).

But go ahead, yunohost will upgrade to buster soon, and it seems that I am a few months late for such an objection :). My bad

**Pull request merged**
