### PR TITLE
update to flask and werkzeug 2.3

### PR DESCRIPTION
**Pull request by azmeuk**
Everything looks fine, there was just a test to edit except for python 3.7

### CODE REVIEW

**Comment by azmeuk** [comment]
Hum. Actually there are some CI tests failing...

**Comment by azmeuk** [comment]
CI is fixed now.

**Comment by zorun** [comment]
While reviewing recent changes to update the changelog, I'm confused about this change: it seems that it does not actually update the Flask dependency, it just updates a test. Is it expected?

**Comment by azmeuk** [comment]
At first it was updating the dependencies too, I suppose the "merge master branch" modified that.

**Comment by zorun** [comment]
Ah right, the merge is the obvious suspect. @almet can you look at what happened?

**Pull request merged**
