### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by gteti**
Wrong Italian translation -> corrections.

### CODE REVIEW

**Comment by Glandos** [comment]
Hi, and thanks for taking care of improving this project!

It would have been better to use the [translation platform](https://hosted.weblate.org/projects/i-hate-money/i-hate-money/it/#overview) to suggest improvements. You can even log in with GitHub credentials if you don't want to create a new account.

Moreover, I see in the last change that you remove a format option (`%(num)` instead of `%(num)d`) which seems incorrect.

**Comment by zorun** [comment]
Indeed, the format string needs to be fixed in the proposed change.

**Review by zorun — CHANGES_REQUESTED** [review]
The format string `%(num)d` must not be changed.

**Comment by Glandos** [comment]
I integrated manually changes into Weblate, pushed as #708. All strings are marked for review, since I'm not fluent in Italian.

**Pull request closed without merging**
