### PR TITLE
Drop python 3.7

### PR DESCRIPTION
**Pull request by azmeuk**
[Python 3.7 reached end of life on 27 Jun 2023](https://devguide.python.org/versions/). This PR removes tests for python 3.7, updates the documentation to reflect the new minimum python version. I also applied [pyupgrade](https://github.com/asottile/pyupgrade) to automatically update the codebase to a more recent syntax: `find ihatemoney conf ihatemoney -name "*.py" -exec pyupgrade --py38-plus "{}" +`.

### CODE REVIEW

**Comment by zorun** [comment]
As usual, NACK for me, at least for as long as Debian buster is supported, and probably even more. That's at least June 2024: https://wiki.debian.org/LTS

Even then, I would need good arguments why supporting Python 3.7 is preventing us from doing something.

People don't necessarily update their server OS very often, and we have to think of downstream packaging such as in Yunohost.

I'll leave this open in case @Glandos @almet want to chime in.

**Comment by azmeuk** [comment]
> As usual, NACK for me, at least for as long as Debian buster is supported, and probably even more.

This is a good point. I did not realized that some supported debian would ship some eol python.

**Comment by almet** [comment]
I share the concerns with @zorun on this. I'm closing, hope it's okay for you @azmeuk

**Comment by azmeuk** [comment]
No problem I totally understand :ok_hand:

**Pull request closed without merging**
