### PR TITLE
Allow to disable/enable member via API

### PR DESCRIPTION
**Pull request by JocelynDelalande**
*EDIT: since then, this is working*

This is not working yet, the `activated` state pushed via API seems not to be saved to DB. But I cannot figure out why.

Any ideas ? Help more than welcome.

I wrote a test, it shows how I would expect it to work.

### CODE REVIEW

**Comment by almet** [comment]
Hey. I managed to make it work with the following changes:

```diff
+++ b/ihatemoney/api.py
@@ -64,7 +64,7 @@ class APIMemberForm(MemberForm):
 
     But we want Member.enabled to be togglable via the API.
     """
-    activated = BooleanField()
+    activated = BooleanField(false_values=('false', '', 'False'))
```

It seems for whatever reason that the `False` value is not converted properly. I'm unsure if it's during the sending by the test client, or if it's when received by the server's view.

**Comment by almet** [comment]
I've digged a bit more on this: it seems that the data we're receiving is not properly formatted: we receive direct strings, rather than JSON-encoded strings.

So, I've read some documentation about how the Flask test-client works, and [it seems](http://werkzeug.pocoo.org/docs/0.13/test/#werkzeug.test.EnvironBuilder) that by default it only sends form-encoded data, which explains why we were not getting the proper values.

The patch for this will probably be bigger than we think, because we will need to change all the calls to the API to specify the `Content-Type` and encode the data to JSON.

```python
res = self.app.post('/api/call, 
                    data=json.dumps(data),
                    content_type='application/json')
```

**Comment by almet** [comment]
Some more thoughts: I believe this API is starting to show its current limits. Instead of accepting JSON as an input, it seems to only support form-encoded data, which doesn't seems right (and probably never was the intent).

I think we should discuss this in the issue about changing how the API is currently generated (#298).

**Comment by JocelynDelalande** [comment]
> Hey. I managed to make it work with the following changes:

Hurray ! thanks a lot for this help ! My eyes slipped over this part of the doc without stopping while debugging.

> Some more thoughts: I believe this API is starting to show its current limits. Instead of accepting JSON as an input, it seems to only support form-encoded data, which doesn't seems right (and probably never was the intent).

I globally agree (API lib change required), but I discovered (by testing) that the API actually accepts JSON request body.

**Comment by JocelynDelalande** [comment]
Ready for merge :-). I let someone else giving a look and merging.

**Pull request merged**
