### PR TITLE
Prepare next release

### PR DESCRIPTION
**Pull request by zorun**

### CODE REVIEW

**Comment by zorun** [comment]
I think it's good to release soon so that @youegraillot 's work on Docker (#919) can be made available.

Some pending changes that I think should also make it into this new release:

- #963 security-related (to be discussed)
- #949 that fixes the rest of the performance issues
- #962 that fixes a validation bug #957
- #956 more UI fixes
- possibly #961 (welcome API feature) if it's ready, but that could also go into a future "feature" release 5.2.0

What do others think?

**Comment by zorun** [comment]
And I forgot about this bug: #948 
But I think we don't have a fix just yet.

**Comment by zorun** [comment]
Updated with latest changes, the next release number will be 5.2.0 (new features).

**Comment by almet** [comment]
So we're good to go here, right?

**Comment by zorun** [comment]
It seems so, thanks a lot @Glandos for fixing the last bugs!

I'll update the release notes and see if we're good to go.

**Comment by zorun** [comment]
I have updated the release notes and everything looks good, but we have a regression that was just reported: #1005

It should be fixed before releasing, it causes an error with the default config on Docker.

**Comment by zorun** [comment]
And release 5.2.0 is out!

**Pull request closed without merging**
