### PR TITLE
Do not require a captcha when using the API

### PR DESCRIPTION
**Pull request by almet**
This was trickier than expected, due to some side effects : when the
captcha is set to `True` via configuration, it doesn't change the
behavior directly of the ProjectForm class, but does so only when the
project form is used in the `web.py` module.

So, when just using the API (and not using the web.py module, for
instance during tests — manual or functional), no problem was shown,
and everything was working properly.

But at soon as somebody sees the "/" endpoint, the captcha was
required, by both the API and the `web.py` module.

This fixes it by adding a way to bypass the captcha with a new
`bypass_captcha` property on the form.

### CODE REVIEW

**Comment by zorun** [comment]
Wow, this is a good heisenbug! Maybe we should get rid of that `enable_captcha` class method to avoid this kind of very subtle issues in the future? Isn't there another way to do this, maybe with form inheritance?

**Comment by almet** [comment]
Hmm, that's correct. I believe we should merge this and change the way we handle this captcha thing in another pull request. I opened a new bug for this.

**Comment by almet** [comment]
Actually, I changed the way things were implemented for the Captcha. It's a lot more clear this way, thanks @zorun for the review :+1:

**Comment by zorun** [comment]
Great, thanks for the change, it looks good :) I think you just need to reformat

**Pull request merged**
