### PR TITLE
Update models: Bill.pay_each()

### PR DESCRIPTION
**Pull request by DavidRThrashJr**
SQL query is faster for summing up weights

### CODE REVIEW

**Comment by Glandos** [comment]
It looks good to me. @Natim or @almet, can you have a quick look?

**Comment by almet** [comment]
That looks good to me, thanks! We currently don't have any unit test for this, but I believe that would actually be needed.

Are you willing to create a unit test testing this scenario? Thanks!

**Comment by Glandos** [comment]
The test looks good to me. Thanks for it!

**Comment by almet** [comment]
Thanks :-)

**Pull request merged**
