### PR TITLE
Position flash messages with CSS rather than JS

### PR DESCRIPTION
**Pull request by JocelynDelalande**
Because I'm in the mood of killing some JS today :-)

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Besides, I'm not satisfied with where the flash messages are positioned in ihatemoney, but that is another story :-).

**Comment by JocelynDelalande** [comment]
Thanks for your review :-)

> There is a small regression though. When I add a new user, I have to wait for the flash message to disappear to be able to click the Add new bill button.

Well seen, I missed this one. I believe this is now fixed :-).

I used a CSS property that is [unsuported on IE <= 10](https://caniuse.com/#feat=pointer-events). IMHO, this is OK (IIRC, IE is auto-updating by default since some time. Result is IE10 have ridiculous usage share).

So, IMHO, no need to use the polyfill (or do somehow else).

WDYT ?

**Comment by 0livd** [comment]
It's now working fine on both Firefox and Chromium. I didn't bother testing on IE but yeah I guess dropping IE 10 support won't hurt much :)

**Comment by almet** [comment]
I agree: we don't really care about internet explorer versions before 10. Thanks for the work on this one, it works perfectly locally, let's merge!

**Pull request merged**
