### PR TITLE
Fix translations.

### PR DESCRIPTION
**Pull request by Natim**
There are a couple of translations that seems broken to me.

### CODE REVIEW

**Comment by zorun** [comment]
@Natim see #576, I think the whole page needs some overhauling to be able to translate it properly

**Comment by Natim** [comment]
> I think the whole page needs some overhauling to be able to translate it properly

Yeah that what I noticed, I tried to look at it, do you see things I missed?

**Comment by zorun** [comment]
It's an improvement! But having things `<a href="#" data-toggle="modal" data-keyboard="false" data-target="#confirm-erase">` in the source to translate looks like it could break lots of things and even introduce XSS :/

There remains lots of strings that are handled through macros (`simple_property_change`, `owers_changed`) and it seems difficult.

Let's discuss on #576 about the best way to improve it and involve the original authors?

**Comment by Natim** [comment]
About HTML tags in the translation files, I believe that's the right way to do it.

I agree that weblate support for it is a bit weird. I like the way LingoHub handles it.

I think we can rely on review or tooling for the XSS matter.

For the macro I agree about involving original authors.

I translated it in French and it didn't seem too complex.

**Pull request merged**
