### PR TITLE
fix: password generation command line crash

### LINKED ISSUE #1241: Generate Password Hash isn't working anymore
When using the latest Docker image, version 6.1.1, it is not possible to create a password, as the application context isn't created.

This could be the breaking change, but I am not too familiar with the project.
https://github.com/spiral-project/ihatemoney/commit/857ca2d5b01c7722016a8bc1fd89324acbfcab55#diff-91addaa276f43da0d54547b88d095bed802e84332616f73e08e218679213842fR455

Here the console output when trying to run `docker run -it --rm --entrypoint ihatemoney ihatemoney/ihatemoney generate_password_hash`, like it is stated in the [documentation](https://ihatemoney.readthedocs.io/en/latest/installation.html#docker):

```
/src/ihatemoney/monkeypath_continuum.py:16: UserWarning: SQLAlchemy-continuum version changed. Please check monkeypatching usefulness.
  warnings.warn(
Password: <entered a password here and pressed Enter>
Traceback (most recent call last):
  File "/usr/local/bin/ihatemoney", line 33, in <module>
    sys.exit(load_entry_point('ihatemoney', 'console_scripts', 'ihatemoney')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/src/ihatemoney/manage.py", line 39, in password_hash
    print(generate_password_hash(password))
  File "/src/ihatemoney/utils.py", line 455, in generate_password_hash
    if current_app.config.get("PASSWORD_HASH_METHOD"):
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```

~The quick fix for now is to just use version 6.1.0 where the hashing still works.~

### PR DESCRIPTION
**Pull request by azmeuk**
Fix a password generation command line crash introduced by #1214 

fixes #1241

### CODE REVIEW

**Comment by almet** [comment]
Merged with latest changes in master.

**Comment by azmeuk** [comment]
I have rebased and edited the PR (`@with_appcontext` needs to come after `@cli.command`).

**Comment by almet** [comment]
Thanks, I was not sure why this was failing :)

**Comment by azmeuk** [comment]
Actually, this has been solved by:

https://github.com/spiral-project/ihatemoney/commit/eb7338c76c6fcbd11ca6ec88679217e7b4b2e997#diff-395aa9b2d6ecd7f89f2770b3ecef6053a905ad7e387df33214ce435714888150

**Pull request closed without merging**
