### PR TITLE
[docker] Add fixed release vs Nightly mode

### PR DESCRIPTION
**Pull request by bnjbvr**
See commit message. Alternatively, the non-Nightly version could just download what's on Pypi; I don't have a clear criteria of choice here.

### CODE REVIEW

**Comment by almet** [comment]
This looks good to me, and having an easy way to install the latest master from github seems a nice idea.

**Comment by almet** [comment]
I would prefer to rely on PyPI rather than on github tags for the download. There is not reason that the packages downloaded from github would be pip-installable.

Defaulting to `pip install ihatemoney` instead seems better to me.

**Comment by bnjbvr** [comment]
I've got local changes to do this, but I am now wondering: this means that the image won't be able to use local code, which could be an issue for development (maybe? some people use Docker for development purposes too). So I'm wondering if I should introduce a third mode (then I'd use an env variable to control this: 1. code gets copied into the Docker image, or 2. pip install or, 3. git clone/update from this repository). Any opinions about this?

**Comment by almet** [comment]
So, I'm not using docker myself for development, so I'm not familiar with how things should be done.

That being said, requirements for dev aren't the same as for "normal" install itself. One should install `dev-requirements.txt` in addition, also requirements are potentially pinned in the `setup.py` but not in the `requirements.txt` files.

Long story short : if we want to also support the "dev" mode, then I think we should run `pip install -e . && pip install -r requirements.txt && pip install -r dev-requirements.txt`.

+1 for having this choice in the docker image if that helps people.

**Comment by bnjbvr** [comment]
Ok, in this case it might even be simpler to propose another Docker image for development purposes, since the current image wasn't thought for development anyways. So I'd prefer this keep the dev feature out of scope for the current PR, if that's fine with you too.

**Comment by almet** [comment]
Okay, that's fine for me, thanks for the dockerfile update!

**Pull request merged**
