### PR TITLE
Test the CI (do not merge)

### PR DESCRIPTION
**Pull request by almet**
So it seems that the CI is not working at the moment. More specifically, docker test doesn't work : it cannot connect to the remote and then fails.

### CODE REVIEW

**Comment by almet** [comment]
I'm not sure what's happening. It works locally when I run the action alone, but doesn't remotely.

Here's the code https://github.com/spiral-project/ihatemoney/commit/ec0a3aa07050a6933d239e64eb7631a64e84d1ff

**Comment by zorun** [comment]
This part of the CI seems to be working again now.

**Comment by zorun** [comment]
Damn, it happened to me today, but it's kind of random.

I believe it's because we don't wait for Ihatemoney to be ready before running the `wget` test.

Simple fix: we could just sleep for a few seconds.

Proper fix: we would need to tell docker-compose about healthchecks and add a dependency between the two containers.

@youegraillot any thoughts?

**Comment by zorun** [comment]
Now fixed by #1139 (hopefully)

**Pull request closed without merging**
