### PR TITLE
api: add bearer token support

### PR DESCRIPTION
**Pull request by eMerzh**
In sharing options, we have a link with a token.
It might be a good idea to have, as API auth method, this token.
so apps can catch those links and use it directly

I think this is probably not enough because it doesn't let the app discover the project id ...
not sure if we need to include some endpoint that does : token => project id
or include project id in clear text in the url...

### CODE REVIEW

**Comment by almet** [comment]
Related to #412, where I suggested to create an endpoint which can generate a new auth token and then accept a new authentication scheme, with the auth token.

**Comment by eMerzh** [comment]
@almet yes can probably relate, but here it was more about using this token than getting one.... Any prefs about the project id?

**Comment by almet** [comment]
Sorry for the delay answering you here! As currently tokens are only generated per project, it makes sense to have a way to find back the project they're related to, for sure.

Including the projectid in the URL seems the simplest way to handle this, so I would go for this, I think!

**Comment by almet** [comment]
@eMerzh hey! Hope you're doing well! Should we move forward on this?

**Comment by eMerzh** [comment]
mmh yes 👍
for me this can still be useful. If you feel the same and have nothing more to fix, let's move it on ;-)

**Pull request merged**
