### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by AzharMithani**

### CODE REVIEW

**Comment by AzharMithani** [comment]
Hope it is helpful :)

**Comment by Glandos** [comment]
Hi @AzharMithani thanks for spending some of your time on this project!

Is there any reason for including a comment with your source code disclaimer? It seems at least out of this project's scope.

**Comment by AzharMithani** [comment]
I saw an issue related to the source code disclaimer so thought that the
link would be helpful but wasn't sure if the issue had been resolved so
included the link in the comment section.

**Comment by Glandos** [comment]
Sorry I'll close this because I find it irrelevant. The first two added comments don't add value, since the code is pretty obvious, and the last one doesn't apply to this project.

**Pull request closed without merging**
