### PR TITLE
Changed the favicon image to something more clear

### PR DESCRIPTION
**Pull request by Sammed98**
This is regarding the issue #543 . I have change the icon to something more clear and on the lines of "I hate money".

### CODE REVIEW

**Comment by Sammed98** [comment]
Could someone tell me why this issue failed? I just changed the favicon image file and no changes to the code were done.

**Comment by Glandos** [comment]
This is because there is a check on python file format, and the tool for that was updated. See #676 

Anyway, small question, did you create the icon yourself, or do you find it somewhere else?

I think this is a nice try. It is at least better than the one we have.

**Comment by Sammed98** [comment]
I got it from [this](https://icons8.com/icons/set/favicon) website.

I read the [#676](https://github.com/spiral-project/ihatemoney/pull/676) request. I did not quite understand it. Is the issue on my side or the application's side as a whole? If it is on my side, what should I change?

**Comment by Sammed98** [comment]
@Glandos could you help with this?

**Comment by Glandos** [comment]
OK, I found the icon page: https://icons8.com/icon/AOp8PJXXHB0i/split-money
I used Icons8 a lot, they have a very nice feature set. However, [their free license](https://icons8.com/license) requires a link to their website. This is not a huge deal, but I think I'd prefer to avoid that.
They have a special case for opensource software, but we should be popular enough to have our Wikipedia page for more than one week, and currently, there is none :)
Do you think you can find another icon that can be free enough to fit our license?

Oh, and don't worry for the failed check. It's an issue due to a misaligned configuration between the project and the CI platform.

**Comment by indatwood** [comment]
Hi, I concur with @Glandos here, I'd rather go with a free license if possible. I'm closing this for now, but feel free to reopen a new pull request with a different icon if you want, of course :-)

**Pull request closed without merging**
