### PR TITLE
Add a .gitlab-ci file in order to run continuous integration on gitlab

### PR DESCRIPTION
**Pull request by aavenel**
Add a simple gitlab-ci for those who prefer to use gitlab instead of github.

It could be interesting to add some staging and deploy environments too.

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
As the project is hosted on github, and the PR can only come from GH, I don't realy see the interest. @aavenel could you elaborate ?

(wether to switch or not to some gitlab instance, but that is another debate)

**Comment by almet** [comment]
Maybe is there an alternative hosting of this project somewhere on gitlab? But in any case I'm not aware of it :)

**Comment by astorije** [comment]
Just my 2c, but please pretty please don't move this project to GitLab (or else). Of course feel free to mirror or fork it there or anywhere else, but actually moving it somewhere else would be harmful to your users who rely on the existing URL/Git repo/history.

**Comment by aavenel** [comment]
Don't worry @astorije, there is absolutely no project of moving/forking this repo to gitlab. I just have a self hosted forge using gitlab that I use for other projects and I was doing some tests about CI. I'll close this PR as it appears not really useful for other people.

**Comment by astorije** [comment]
Gotcha! 😅
And hi btw, funny to see you guys more often on the Interwebs than IRL :D

**Pull request closed without merging**
