### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by almet** [comment]
Nice one, thanks!

This raises the question of having things translated in the future. I know there are tools such as transifex, maybe should we integrate with it?

Also, we probably should have a list generated on the fly with the supported translations, and a way for the end user to switch to all these languages (currently we only support english and french in the menu).

**Comment by Vistaus** [comment]
You're welcome! :)

Yes, it would be great if you could integrate with a translation tool! There are a couple of ones, such as Transifex, Weblate, OneSky and Crowdin. I personally prefer Transifex though, but feel free to choose one of the others if you think they suit your project better :)

**Comment by Glandos** [comment]
In this list, the most FLOSS compatible is Weblate.

**Comment by almet** [comment]
> In this list, the most FLOSS compatible is Weblate.

I've just contacted them and asked for a free plan :-)

**Comment by Vistaus** [comment]
Cool! :) Let me know when it's approved so I can sign up on your Weblate instance to receive notifications when strings are updated :)

**Comment by almet** [comment]
Here we go! https://hosted.weblate.org/settings/i-hate-money/i-hate-money/

**Pull request merged**
