### PR TITLE
introduce chat feature(beta) in ihatemoney

### PR DESCRIPTION
**Pull request by Dr-blue-cyber**
chatbox skelton from git repo 
https://github.com/hitchcliff/front-end-chatjs

### CODE REVIEW

**Comment by Glandos** [comment]
Could you elaborate on what do you exactly want to do?

I see that this link to a "chat box", but the code actually does nothing, it just shows a web page, without any interaction.

And I think that IHateMoney doesn't need such a feature anyway.

**Comment by zorun** [comment]
I also don't think it's a useful feature for I Hate Money. We already have too many features for my taste, see also https://github.com/spiral-project/ihatemoney/discussions/767

**Comment by Dr-blue-cyber** [comment]
I think something messed around with my files,I need to work to fixed the issue

**Comment by almet** [comment]
Hi @Dr-blue-cyber, thanks for your efforts on this. But unfortunately, I also don't think we should add a chat feature to Ihatemoney. Not that it's not valuable to anyone — if you did it, you probably have an use-case for it — but one of the goals of the project is to keep the feature set minimal.

I'm going to close this, but if you feel that's a really needed feature and that we're making the wrong move here. Don't hesitate to open a discussion on it.

Cheers!

**Pull request closed without merging**
