### PR TITLE
Adding Graphs to Statistics Tab (Issue #136)

### PR DESCRIPTION
**Pull request by mmushtaq201**
Fixes # 136 [https://github.com/spiral-project/ihatemoney/issues/136](url)

This pull request involves code for Issue 'Display statistics as a graph #136'. Details of the implementation is as follows:

1. Two graphs have been implemented using AnyChart - JS charts.
2. First Graph displays statistics of total money spent by each participant for a given the project.
3. Second Graph displays statistics of the combined monthly expenditures of all the participants for a given project.
4. Changes reside only in the .html files:
- statistics.html
- layout.html
5. To my knowledge, there is no impact on the existing functionality of the project.

**Existing Project Credentials for ready to view graphs.**
**Project Identifier:** test
**Project code**: admin1234

### CODE REVIEW

**Comment by Glandos** [comment]
AnyChart is probably a good product but it [requires a license](https://www.anychart.com/buy/non-commercial-license/).

I can't speak for other members, but I am personally against its integration for this reason.

**Comment by zorun** [comment]
Thanks for working on this!

I'm not sure the first one brings a lot of useful information, but the second one is good. How does the user choose which one to display?

And indeed, it seems that AnyChart is not free software. We probably cannot use it without asking for a special license and I don't like that either.

**Comment by almet** [comment]
I'm closing this in favor of the most recent #731 attempt with another library.

**Comment by almet** [comment]
But, let me stress this out : thanks a lot @mmushtaq201 for working on this. That's appreciated.

**Pull request closed without merging**
