### PR TITLE
List supported currencies in API under api/currencies

### PR DESCRIPTION
**Pull request by petermaksymo**
For #847 

Returns a list of supported currencies under `/api/currencies`.

This is my first PR for this project, any feedback is greatly appreciated :)

### CODE REVIEW

**Comment by almet** [comment]
Hi, thanks for opening a pull request here. It's appreciated :-) I think adding a test for this would be helpful in order to test that it's behaving the way we think it is.

Let me know if you need help on how to do this properly.

**Comment by petermaksymo** [comment]
Thanks for the feedback, I'm happy to add some tests. 

Just to confirm before I do it, I'm thinking of putting them at the start of this [test_currencies](https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/tests/api_test.py#L578) and add asserts for a good status and check that `XXX` is within the list. Anything else I should look for?

**Comment by almet** [comment]
Please, add them in the api tests instead, it's better to keep all the API-related tests together.

**Comment by almet** [comment]
Works for me, thanks! We can merge as soon as the build is green :-)

**Comment by almet** [comment]
Thanks :-)

**Pull request merged**
