### PR TITLE
Change Dockerfile to compile python dependencies at build time.

### PR DESCRIPTION
**Pull request by wrecker**
WIP PR for #792

### CODE REVIEW

**Comment by zorun** [comment]
This looks good so far, thanks. You can remove the NIGHTLY variable as it's now unused (it's the default)

I'm not convinced we want to keep the old Dockerfile around. For release builds we should probably just build it once and publish it on the dockerhub or something.

Can you also have a look at the documentation and see what needs to be updated? https://ihatemoney.readthedocs.io/en/latest/installation.html#with-docker

I see you bump Flask-SQLalchemy, why did you need that?

**Comment by wrecker** [comment]
> I see you bump Flask-SQLalchemy, why did you need that?

I ran into this SQLAlchemy issue that was causing the startup to fail https://github.com/pallets/flask-sqlalchemy/issues/910#issuecomment-802098285

**Comment by wrecker** [comment]
Ok. Made the changes to remove the original Dockerfile and updated the Docker section of the docs.

**Comment by zorun** [comment]
Thanks. You need to squash your commits before you rebase to master, otherwise you'll get conflicts.

Here are some more suggestions:

- add `.git/` to a `.dockerignore` file to avoid including 40 MB of git history for nothing
- remove all apk packages: there's no need for them now
- `generate_hashed_password` in the doc looks like a typo, it should be `generate_password_hash`

**Comment by wrecker** [comment]
> You need to squash your commits before you rebase to master, otherwise you'll get conflicts.

Done.

> Here are some more suggestions:
> 
>     * add `.git/` to a `.dockerignore` file to avoid including 40 MB of git history for nothing

Good tip!. Done.

>     * remove all apk packages: there's no need for them now
> 
Done.

>     * `generate_hashed_password` in the doc looks like a typo, it should be `generate_password_hash`
Done.

**Comment by zorun** [comment]
Excellent, thanks!

**Pull request merged**
