### PR TITLE
Fix bad export filename

### PR DESCRIPTION
**Pull request by 0livd**
Use project.id in export filename as it is already slugified

### CODE REVIEW

**Comment by almet** [comment]
Not sure why the tests are failing, it seems unrelevant to your changes.

**Comment by 0livd** [comment]
Yeah don't know why this was not failing before .... I actually fixed this failing test in #178 with 10a16a3b5cf13ca6ca2a1f060901b2bc943098ca . The first time I saw it failing was after 108970eb503f503b764408b0f93fde87d67a776d so I thought it was not executed because of the tab indentation but apparently it is something else ...

**Comment by almet** [comment]
Neat, this can be rebased now :-)

**Comment by almet** [comment]
Thanks again for your energy on the projet, that is very appreciated!

**Pull request merged**
