### PR TITLE
Change mobile link icon to point to Play Store (#597)

### PR DESCRIPTION
**Pull request by Abo7atm**

### CODE REVIEW

**Comment by eMerzh** [comment]
not sure we want to do that 🤔 .
the idea here was to link to the "project" of the mobile app where scrolling a bit might link you to the download link you want, but money buster prefers (i think) f-droid to play store.

**Comment by zorun** [comment]
We should definitely add a link to the F-Droid app, and maybe also another link to the play store. Maybe the icons could be adapted?

**Comment by Glandos** [comment]
> not sure we want to do that thinking .
> the idea here was to link to the "project" of the mobile app where scrolling a bit might link you to the download link you want, but money buster prefers (i think) f-droid to play store.

I agree @eMerzh but on the other hand, the goal is to make a smooth experience here.

Maybe we can add a dropdown with the 2 options, shown when clicking the link? But it's clearly more work.

**Comment by zorun** [comment]
The most user-friendly way is to add two links with appropriate icons: one for F-Droid and one for the Play Store. But indeed we may want to link to the "project" instead.

In that case, we could at least use a more user-friendly link:

- https://gitlab.com/eneiluj/moneybuster#moneybuster-for-android : already better than the current link (it starts with a short description of the app, and if you scroll a bit you quickly see the big F-Droid and Play Store buttons)
- https://gitlab.com/eneiluj/moneybuster/-/wikis/home#releases : direct access to the packages, we support the project because there's a Donate button, and there are screenshots. However, it's missing a description of the app

**Comment by indatwood** [comment]
> The most user-friendly way is to add two links with appropriate icons: one for F-Droid and one for the Play Store.

I second this :-)

**Comment by Abo7atm** [comment]
Interesting discussion. I get, now, what's intended from the mobile app button.

> The most user-friendly way is to add two links with appropriate icons: one for F-Droid and one for the Play Store.

This might be a more user-friendly option, but, as mentioned above, the intention of using this button is to link to the project itself, while still keeping the nerdy-ness to a minimum. 

> * https://gitlab.com/eneiluj/moneybuster#moneybuster-for-android : already better than the current link (it starts with a short description of the app, and if you scroll a bit you quickly see the big F-Droid and Play Store buttons)

I think this might be the better choice.

**Comment by eMerzh** [comment]
@Abo7atm thanks for the modifcations :)

lgtm 👍 ... we might think in the future about having a dedicated page or smth for the integrations...

**Comment by eMerzh** [comment]
btw we might ask money buster if they'd like to create a nice welcome page

**Comment by indatwood** [comment]
@eneiluj do you have a preference?

**Comment by almet** [comment]
Thanks ! Should we point to the « install » buttons directly instead? with this link https://gitlab.com/eneiluj/moneybuster#install

**Comment by Natim** [comment]
Yes I thought it was the case already but that's definitely a good idea

Le ven. 8 mai 2020 à 23:03, Alexis Metaireau <notifications@github.com> a
écrit :

**Comment by JocelynDelalande** [comment]
> Thanks ! Should we point to the « install » buttons directly instead? with this link https://gitlab.com/eneiluj/moneybuster#install

Not sure, I tend to avoid directing users to README, even if it is on the right anchor. IMHO We have to stop thinking people feel safe/welcomed in a gitlab/github page. Those are complex interfaces intended for developers. That is what those interfaces are good at.

**Comment by indatwood** [comment]
If we don't feel like putting a link on the readme (even with the right anchor) then we might want to create a page on the ihatmeoney website / project so that users can find the different options :-)

**Comment by indatwood** [comment]
What should we do with this? My insight would be to merge it but still create a new page linking to clients.

**Comment by Glandos** [comment]
It's clearly better than the current situation, even if not ideal.
@JocelynDelalande I tried the new link with a "mobile" screen (using Firefox responsive feature), and it doesn't look as nerdy as on desktop screen. Do you think we should skip this request or keep it?

**Comment by almet** [comment]
Hey, I believe we're good to go here :-) We can still add new enhancements in the future if needed! Let's merge?

**Comment by zorun** [comment]
It's not perfect but it's better than before, so let's merge!

**Pull request merged**
