### PR TITLE
Py3 port

### PR DESCRIPTION
**Pull request by FabriceSalvaire**

### CODE REVIEW

**Comment by Glandos** [comment]
Is it backward compatible with python 2.7? It seems not, given the substitution from 'unicode' to 'str', but my question is more about Flask itself, since I don't know if those changes are for python 3.x only.

**Comment by FabriceSalvaire** [comment]
Tests are broken for py3 and a256bca39854b197829c51d426c42084d5cc0637 should be rewritten so as to be backward compatible with py2.

Other commits are fine.

**Comment by almet** [comment]
Thanks for taking the time to do this! I definitely want to have python 2.7 compatibility here, so if you manage to make it work, I'll gladly merge this.

**Comment by FabriceSalvaire** [comment]
The incompatibility comes from the poor unicode support of Python 2. We could manage these few lines with:

```
import sys
if sys.version_info < (3,):
    ...
```

else we have to use helpers. I don't have so much experience on this since I stopped to write and support Python 2 codes.

**Comment by almet** [comment]
That's one way to do it yes! I have no idea what's the best way to handle this, to be honnest. @natim is my python 3/2 expert here, so he might have good advice?

**Comment by JocelynDelalande** [comment]
>else we have to use helpers. I don't have so much experience on this since I stopped to write and support Python 2 codes.

You way want to use six for that job :)

**Comment by Natim** [comment]
> You way want to use six for that job :)

+1

**Comment by JocelynDelalande** [comment]
@FabriceSalvaire gentle bump :)

**Comment by almet** [comment]
Hi, thanks @FabriceSalvaire for your efforts here. Would you like to take this further, or should we close the issue instead? Or maybe someone would like to take this over?

**Comment by FabriceSalvaire** [comment]
I don't have time to work on this actually. It could be probably achieved in few hours but unicode and 2/3 portability are headache stuffs.

**Comment by JocelynDelalande** [comment]
@FabriceSalvaire Thanks for taking the time to explain you won't have time, that is appreciated.

Inaugurating a new label for that case to nofity people, this PR is looking for some love.

**Comment by almet** [comment]
Superseded by #178

**Pull request closed without merging**
