### PR TITLE
Ajouts au changelog 5.0

### PR DESCRIPTION
**Pull request by JocelynDelalande**

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Honêtement, j'ai pu en manquer certains dans le git log , mais j'en aurais au moins attrapé une partie.

Pas clair pour moi : les numéros que l'on met dans le changelog, cesont des n° de ticket ou de PR ?

**Comment by Glandos** [comment]
Quand il y a une PR, le numéro de PR, sinon le ticket, avec l'identifiant version courte du commit.

**Comment by JocelynDelalande** [comment]
OK, merci pour l'éclaircissement :) peut-être qu'on pourrait l'écrire quelque-part.

J'aurais instinctivement pensé l'inverse : le changelog est utile aux admins et aux curieux·se·s, la PR ne l'est qu'aux dévs.

**Comment by zorun** [comment]
Thanks for spotting the missing entries!

I believe these two are already in the changelog for 4.1.4 so they can be omitted for 5.0:

- Fix bug on tool-tip message
- Change the color of the add a member button

I admit it can be hard to be sure because of the backports.

**Comment by JocelynDelalande** [comment]
> Thanks for spotting the missing entries!

Thanks for spotting my spotting issues ! 🤪

PR is fixed. Archeologists will thank us ;-)

**Comment by indatwood** [comment]
Hi, thanks for this! Where are we with this? Should we merge it and then release 5.0?

**Comment by Glandos** [comment]
I'll wait for a resolution of #597 (via #688 if everything goes well) and merging of #661.

**Comment by zorun** [comment]
I had completely forgotten that 5.0 is still not released :/

For the changelog, we have two new translations: Portuguese and Japanese.

We have a milestone with a list of bug / PR that should be part of 5.0: https://github.com/spiral-project/ihatemoney/milestone/5

Of course it's open to discussion. Those that seem important to me:

- #659 is a bug fix, but I think it's stuck. If we don't find an easy way to fix it, we shouldn't delay the release because of it (just add as known issue in changelog)
- #656 is a UX regression and should be fixed (in my opinion)
- #587 would improve translations, but it needs time for all translators to adapt. We can either merge it and wait a few weeks before releasing, or keeping it for another release. I think I prefer keeping it for another release.

**Comment by zorun** [comment]
And of course, there's #599 / #661 which is really tricky...

**Pull request merged**
