### PR TITLE
Optimise sql queries

### PR DESCRIPTION
**Pull request by zorun**
These two commits mostly fix issue #159.

### CODE REVIEW

**Comment by aavenel** [comment]
Just tested your branch, with a database of 1000 bills. This is really good ! I was going to run some numbers to show the improvements, but I saw you already have a nice summary on your commit message.
 :shipit:

**Comment by almet** [comment]
Really good numbers here, thanks!

**Comment by aavenel** [comment]
@almet Does this PR has been deployed on ihatemoney.org ? The website is still a bit slow unfortunatly

**Comment by almet** [comment]
It wasn't deployed, but I just did it, thanks for the poke!

**Pull request merged**
