### PR TITLE
Integrate flask-limiter

### PR DESCRIPTION
**Pull request by Glandos**
For the moment, it's just the integration of flask-limiter instead of the old and hand-made LoginThrottler.

Open discussion: since we are about to use limiter in more places than admin login, I modified the main layout to display limit breached. But… should we displayed the content block in this case? Or just optionnally, based on some variable?

### CODE REVIEW

**Comment by Glandos** [comment]
By the way, Flask-Limiter is Python>3.6

**Comment by almet** [comment]
We probably shouldn't display the content block if we reached the max limit.

Should we merge this?

**Comment by Glandos** [comment]
Here you are!

Yes, I also agree that the content block shouldn't be displayed. At first, I didn't implemented a message in the template, so I relied on the content block to explain why it was blocked.
But now… we could just not show it.

By the way, I will first merge #1083 first, to be sure tests are OK on 3.7+

**Comment by almet** [comment]
Crap, I merged without wanting to. Hope things will be okay.

**Comment by Glandos** [comment]
It's Python: better ask for forgiveness than for permission!

Joke aside, we can revert it if needed. Or better: improve it!

**Pull request merged**
