### PR TITLE
Update Python

### PR DESCRIPTION
**Pull request by Glandos**
- [X] Drop Python 3.6
- [x] Use Python 3.11
- [x] Increase version

### CODE REVIEW

**Comment by Glandos** [comment]
@almet @Natim @zorun Do you have any strong opinion about this?

**Comment by Natim** [comment]
I think we could drop support to 3.7 too.

**Review by Natim — APPROVED** [review]

**Comment by Glandos** [comment]
For me… Yes, we can. But since all our dependencies still supports 3.7, it's nearly effortless. For now!

**Comment by almet** [comment]
:+1:

**Pull request merged**
