### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/i-hate-money/i-hate-money/) for I Hate Money/I Hate Money.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Glandos** [comment]
@pratyush3124 Are you really trying to translate?

**Comment by almet** [comment]
Yeah, this is odd, the diff looks quite empty of strings on the target language.

**Comment by pratyush3124** [comment]
@Glandos I am no longer working on the translation sorry for the inconvenience

**Comment by Glandos** [comment]
OK, no problem then, I was just curious about this PR spam ;) I deleted the language, but feel free to recreate it if you have more time!

**Pull request merged**
