### PR TITLE
Rework invite people to project

### PR DESCRIPTION
**Pull request by eMerzh**
Hey, another small improvement here (at least i think 😉 )

Summary:
- small ie fixes for icons
- move send invite links to right side with participants
- change some labels
- add some icons
- split send invite explanation into distinct methods
- tiny improvements on send email form

Before:
image

After:
image

Before:
image

After:
image

please check the wording and if you like the split ... i was feeling that the previous text was a bit long-ish and messy (here you can send invite, or password, but put emails down there , or you can use the link, here is the form )

### CODE REVIEW

**Comment by Glandos** [comment]
Nice improvement.

In my opinion, I would shorten the wording for the invite button, like "Invite people". This will help the button to be displayed on small screen.

I would also remove exclamation mark from the new participant form and the invite button. I know this make the thing more "dynamic", but then, you don't know where to put them, or even if they still have some meaning at all.

For the invite form, I think that splits are a good idea, but it brings a lot of white space now. What do you think if you keep it, but put the text of each split at the right of each split title?

**Comment by eMerzh** [comment]
@Glandos , agreed the text is too long and does not need exclamations marks changed.
i'll see if i can do smth for the whitespace 🤔

**Comment by eMerzh** [comment]
@Glandos 
smth like that?
image

**Comment by Glandos** [comment]
Exactly! I didn't even know how to clearly mark each split, but the `hr` line is good.

**Comment by eMerzh** [comment]
pushed :)

**Comment by eMerzh** [comment]
aaarrrrg shit! 
said pushed but of course my final table is not pushed ... 🤦‍♂ what a ...
i'll make a small mr about that...
the rest is ok though :)

**Pull request merged**
