### PR TITLE
Fix: Change tool-tip message for access code

### PR DESCRIPTION
**Pull request by rajat641**
This is a fix for Issue [#610 ](https://github.com/spiral-project/ihatemoney/issues/610)
I have updated the message and tested locally.

### CODE REVIEW

**Comment by Glandos** [comment]
Thanks for this modification! In my opinion "logged in" would be better than "log-in" in this case, what do you think?

I am also wondering if it's worth saying that the code is needed to access the project on a new computer. It's normally obvious, and it will make the tooltip longer for nothing. Any opinion?

**Comment by rajat641** [comment]
> Thanks for this modification! In my opinion "logged in" would be better than "log-in" in this case, what do you think?
> 
> I am also wondering if it's worth saying that the code is needed to access the project on a new computer. It's normally obvious, and it will make the tooltip longer for nothing. Any opinion?

**Comment by rajat641** [comment]
@Glandos - i think you're right we can simply add `Use this code while loggin`

**Comment by rajat641** [comment]
I think there is no need for any message on the tooltip. @Glandos - Just thought about your point above and it makes a lot of sense.

**Comment by rajat641** [comment]
Hi  @almet @comradekingu @Glandos 
Can you please help in knowing a proper tooltip message. Its been pending for a while now. I would appreciate your response.

**Comment by Glandos** [comment]
Hi @rajat641 I'm deeply sorry for this late answer. You can imagine that working on my free time is sometimes not as much as I'd like…

Anyway, thanks for your final string, it meets all needed requirements to me. And thanks @comradekingu for his suggestion.

**Comment by zorun** [comment]
It's been pending for only 5 days, I would not call that a long time...

This breaks the javascript code and doesn't display because it's missing escaping: `Don\\'t` instead of `Don't`.

The current text is quite good and short, but it should use "private code" instead of "access code" for consistency. Also, I would say "choose" instead of "make", something like this:

> Don\\'t reuse a personal password. Choose a private code that you can share with your friends.

@rajat641 can you fix in another pull request?

**Comment by indatwood** [comment]
Hey @zorun! The best way to not forget about this is probably to open a new issue (if it's not done already!)

Cheers :-)

**Comment by rajat641** [comment]
Hi @indatwood @zorun @Glandos ,
I have raised the Issue and linked my PR with that. It was really a silly bug from my end.
I should have re-tested it again after the change but I got a little lazy about it.
Also, I'll be a little more patient in the future about code reviews as now I know that you guys work on this in free time.

**Pull request merged**
