### PR TITLE
Enhance bill form

### LINKED ISSUE #656: Show "External link" less prominently when creating bill
Since #479, it is possible to add an URL as "External link" when creating a bill.

However, the field is really big and prominent in the bill creation page, even for people that do not need this feature.

It would be good to find a less prominent design, so that:

- people that don't need External links are not bothered by the additional interface
- people that need External links can still easily add them

A more general discussion about optional features is at #603 (see the example about the weights, I really like it)

### PR DESCRIPTION
**Pull request by Glandos**
Fix #656

Rework UI for new bill form. Additional options are hidden by default (currency and external link)
I also tried to make multiple columns of payee, but this is still WIP

### CODE REVIEW

**Comment by Glandos** [comment]
Here is a quick overview of what changed:

https://user-images.githubusercontent.com/297578/124924197-7a811f80-dffb-11eb-9966-adbacae9fea7.mp4

**Comment by zorun** [comment]
It looks really good! :+1: 

Just one thing, are you sure about "noone"? I would write it "no one", or just keep "nobody" like it was before.

**Comment by Glandos** [comment]
[**@zorun**](https://github.com/zorun) commented on [9 juil. 2021 à 01:38 UTC+2](https://github.com/spiral-project/ihatemoney/pull/783#issuecomment-876810525 "2021-07-08T23:38:35Z - Replied by Github Reply Comments"):
> It looks really good! :+1: 
> 
> Just one thing, are you sure about "noone"? I would write it "no one", or just keep "nobody" like it was before.

Yes, it sounds odd, but it is valid. My quick online research found that "Everyone/Noone" is more formal than "Everybody/Nobody", and we were already using "Everyone" and "Everyone but XXX,YYY" in the bill list. So I chose to stick to the same wording. "Noone" was not used, but it is aligned with "Everyone".

And… as I type this message, I found that "Noone" is accepted by some translation machines, but they always produce "No one" with a space. I'll use that form, this is more eye-friendly.

**Comment by zorun** [comment]
Thanks! Yeah "noone" without space looks weird.

**Pull request merged**
