### PR TITLE
WIP: Upgrade to bootstrap 4

### PR DESCRIPTION
**Pull request by JocelynDelalande**
Upgrade to Bootstrap 4 (see #168 )

## Included
To summarize :

- better factorization of templates
- fix moving elements (ex: try switching from project page to home page, things in sidebar are moving)
- improve readability
- fix misaligned elements
- make more use of BS grid system
- better screen readers/aria support 

## Still on my TODO before it could get mergeable.

- [x] the calendar for date selection is appearing under the bill adding modal
- [x] fix datepicker language loading race condition
- [x] fix datepicker arrow icons
- [x] Add a scrollbar if the content is too big for the modal (intead of overflowing)
- [x] (chrome browser only) When you click on "add a bill" and then close the modal window, everything in the background shift a little bit.
- [x] Weird color changing of the font color when clicking « Add bill » button
- [x] Hovering a member « Reactivate » button shifts everything towards right on the sidebar
- other items reviewers will find :-)

## May come later in a separate PR

- responsive design (this PR only offers decent display for huge/medium display, not for small/tiny ones) @aavenel offered its help.
- rethink the navbar so that its contents is placed less weirdly (I tried to keep the previous philosophy, with minor adjustements).

Reviewers/testers are more than welcome :-) (poke @aavenel & others)

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Finaly got a working datepicker :-)

… Anyway, I ran into something strange : the translation js file (for french translation of datepicker) seems not loaded yet when the `<script>` tag containing the call to `$('.datepicker').datepicker()` happens. Resulting in the calendar not being displayed in french.

I cannot manage to get sure that the translation is loaded *before* `$('.datepicker').datepicker()` is called.

What works is putting the content of the translation file directly in the `<script>` tag before `$('.datepicker').datepicker()`. But it's not something I want to do.

**Help apreciated** on this point :-)

**Comment by aavenel** [comment]
Awesome work :)

I just did a quick review of the UI, here are some points : 

- The modal window for "Add a bill" is too short :
image

- When you click on "add a bill" and then close the modal window, everything in the background shift a little bit.

**Comment by JocelynDelalande** [comment]
Ok, fixed my own bugs with datepicker (the bug was mainly me being stupid :-)

@aavenel thanks, added your bugs to my todo-list (the second seems a chrome-only one)

**Comment by JocelynDelalande** [comment]
@aavenel I think my latest commit fixed your two issues ; could you confirm ?

Meanwhile, I found other CSS bugs…

**Comment by JocelynDelalande** [comment]
@aavenel My TODO is empty :-) could you validate that it seems ok to you ?

@almet Would you have time for a second review before merging, just to get sure that I didn't go accidentally against some choices you made for example ?

Exciting!

**Comment by almet** [comment]
I just tried it on my machine and it looks great. Everything seems a bit bigger, which I'm not sure we want or not. 

A few things that we might want to change (maybe not in this PR though):
- "flash" messages seem not really readable. We might want to use a different way to show them;
- On a small screen, the homepage doesn't fit in one screen (it did previously). Not sure if we want that. I like the idea of having everything on one page, but that doesn't really matter I guess?

In general, thanks for the work :)

**Comment by JocelynDelalande** [comment]
Thanks for taking time to review :-)

> I just tried it on my machine and it looks great. Everything seems a bit bigger, which I'm not sure we want or not.

My feeling is that is seems a bit more in sync with current "fashions" (technically, is not only fashion, but also better usability on touch devices, more DPI on recent screens…). Side-note : I won't personally start modifying bootstrap defaults for margin/font-sizes/button-size/paddings… etc. 

Bootstrap allows to be lazy and to get something nice both to the eye and for ergonomy, that is its point of using it, isn't it ? :-)



> "flash" messages seem not really readable. We might want to use a different way to show them;

Just re-tested, I don't see how they are less readable than before, could you detail/screenshot the issue ?

> On a small screen, the homepage doesn't fit in one screen (it did previously). Not sure if we want that. I like the idea of having everything on one page, but that doesn't really matter I guess?

The homepage seems totally ok down to 1000px, which seems acceptable IMHO… At least for the moment, and until #113 gets done :). At what screen size did you find it non-fitting ?

**Comment by aavenel** [comment]
Looks great ! Good to merge for me, just a few nitpicks here : 

On firefox, I've a strange thing on "Payer" field. There is 2 kind of arrows for the dropdown menu.
image

I've still some king of shifting when I click on "Add a bill" button. I think this is due to the scrollbar being hidden in modal view, such changing the width.

**Comment by almet** [comment]
My screen is a 13'' with a resolution of 1366*768, but as you say, it should be fixed by #113 .

For the flash messages, I believe it's not introduced by your changes, I just noticed that it could be better. It should be handled in another issue, don't bother :)

Great work, thanks!

**Comment by JocelynDelalande** [comment]
> My screen is a 13'' with a resolution of 1366*768, but as you say, it should be fixed by #113 .

weird, could you screenshot ?

**Comment by almet** [comment]
selection_001
Here we are :)

**Comment by JocelynDelalande** [comment]
> weird, could you screenshot ?

I genuinly don't see what is wrong on the screenshot :-/

**Comment by almet** [comment]
Two things: there is a scrollbar, and the "getting started" button on the bottom right doesn't show up (not enough space).

**Comment by almet** [comment]
here is the part that's not show on the first screenshot
selection_001

**Comment by JocelynDelalande** [comment]
> here is the part that's not show on the first screenshot

Oook, it's a vertical issue :-). 

So, from my point of view, that vertical scrolling is fine, I'm afraid we disagree :x.

Are you ok for merge as-is and maybe find something else later if it's important to you ? :-/

**Comment by almet** [comment]
> Are you ok for merge as-is and maybe find something else later if it's important to you ? :-/
Yes, sure ! As stated previously, I'm nitpicking here, thanks for your efforts :-)

**Comment by almet** [comment]
This is now deployed at https://ihatemoney.org/ Thanks for your work :-)

**Comment by JocelynDelalande** [comment]
Cool, thanks ! I'm proud to bring things to ihatemoney :))

@aavenel you turn on #113  ;-)

**Pull request merged**
