### PR TITLE
Update the email template to feel more inclusive.

### PR DESCRIPTION
**Pull request by almet**

### CODE REVIEW

**Comment by Glandos** [comment]
Erf… I don't know why action failed. It says that module `dateutil` is not found, but it is part of the standard library…

**Comment by almet** [comment]
That's weird, but adding it as a direct dependency fixes it. I wonder if some dependency we used dropped its use?

**Comment by almet** [comment]
Ah nice, I didn't know about `pip show` =D.

Is it okay for you if we merge this as part of this PR?

**Comment by Glandos** [comment]
It's not conventional, but the merge will link here for explanation. Let's go.

**Pull request merged**
