### PR TITLE
Changed Font Size of the Logo

### PR DESCRIPTION
**Pull request by HarshVT8999**

### CODE REVIEW

**Comment by Glandos** [comment]
Could you explain us why this change is needed or useful to you?

**Comment by HarshVT8999** [comment]
To increase the font size and intern increasing the logo size.

**Comment by Glandos** [comment]
OK, here are screenshots for comparisons:

Original:
image


Current modification:
image

As a suggestion, by removing vertical padding on application name to get the same navbar height (set `py-0` on the `<a>` tag):
image

It's not a undesired change, but I personally find the logo too big (hence the padding removal suggestion). I guess that with `1.5rem` it should be enough.

Here is a quick animation tour:

https://user-images.githubusercontent.com/297578/132107199-6047a1b8-2673-4d36-9714-bab5cb3997e7.mp4

**Comment by HarshVT8999** [comment]
1.5rem Size looks better!!!

**Comment by almet** [comment]
Okay, should we go ahead with this?

**Comment by almet** [comment]
Done!

**Comment by HarshVT8999** [comment]
Great! Hopefully, you liked the change as well.

**Pull request merged**
