### PR TITLE
Allow using PostgreSQL with docker image

### LINKED ISSUE #924: Using docker image with postgres
Hey there! 

I would like to use the docker image with a PostgreSQL database, but `psycopg2` is not installed in the docker image.

I tried adding it afterwards by running from a simple local Dockerfile like this:

```Dockerfile
FROM ihatemoney/ihatemoney:5.1.1
RUN pip install --no-cache-dir psycopg2
```

But building fails:

```
Step 1/2 : FROM ihatemoney/ihatemoney:5.1.1
 ---> 08d796f3a6e6
Step 2/2 : RUN pip install --no-cache-dir psycopg2
 ---> Running in cdb4fb5e4801
Collecting psycopg2
  Downloading psycopg2-2.9.2.tar.gz (380 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z6s31rox/psycopg2_907bd598618b4dd796894dbecda3d67b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z6s31rox/psycopg2_907bd598618b4dd796894dbecda3d67b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1wer96lf
         cwd: /tmp/pip-install-z6s31rox/psycopg2_907bd598618b4dd796894dbecda3d67b/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-1wer96lf/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-1wer96lf/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-1wer96lf/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-1wer96lf/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-1wer96lf/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/ed/79434011d773e5ea4c51262f6ebfb86680c2908d7677f31ebccd5aa9f1b3/psycopg2-2.9.2.tar.gz#sha256=a84da9fa891848e0270e8e04dcca073bc9046441eeb47069f5c0e36783debbea (from https://pypi.org/simple/psycopg2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading psycopg2-2.9.1.tar.gz (379 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z6s31rox/psycopg2_a59a9d084ba24aaeaf5077bcf4323ec0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z6s31rox/psycopg2_a59a9d084ba24aaeaf5077bcf4323ec0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-acubs1ih
         cwd: /tmp/pip-install-z6s31rox/psycopg2_a59a9d084ba24aaeaf5077bcf4323ec0/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-acubs1ih/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-acubs1ih/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-acubs1ih/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-acubs1ih/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-acubs1ih/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/aa/8a/7c80e7e44fb1b4277e89bd9ca509aefdd4dd1b2c547c6f293afe9f7ffd04/psycopg2-2.9.1.tar.gz#sha256=de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c (from https://pypi.org/simple/psycopg2/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
There is a lot more output which seems to be pip trying to install previous versions of psycopg2.

I don't have a lot of experience with python, so I'm not really sure how to solve this. Maybe it would be best to install the dependency in the default docker image so it can be used with postgres out of the box?

### PR DESCRIPTION
**Pull request by Nikos410**
Install `psycopg2`, which is needed to access a PostgreSQL database.

Resolves #924

### CODE REVIEW

**Comment by zorun** [comment]
Thanks for the patch. Can you measure the additional time needed to build the image? And the resulting size increase? If the size increases a lot, we might want to simply use a debian-based image and install the binary psycopg2 package (see #924)

Also, the doc mentions that the docker image does not support postgresql, it needs to be updated :)

**Comment by Nikos410** [comment]
Will do :)

**Comment by Nikos410** [comment]
See https://github.com/spiral-project/ihatemoney/issues/924#issuecomment-975375414

**Comment by Nikos410** [comment]
Superseded by #919

**Pull request closed without merging**
