### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/i-hate-money/i-hate-money/) for I Hate Money/I Hate Money.

### CODE REVIEW

**Comment by zorun** [comment]
Nice, the Russian translation is 100% complete!

It will have to be adapted for #587 but I suggest we merge the current version to avoid source string conflicts. Also, the current translation can be easily backported for #588 .

**Comment by Glandos** [comment]
I was waiting for Italian, but it seems that it was just created. Let's merge it for Russian then.

**Comment by zorun** [comment]
Thanks!

**Comment by zorun** [comment]
Strange, weblate now complains of a merge conflict in the Russian translation: https://hosted.weblate.org/projects/i-hate-money/i-hate-money/#alerts

Maybe the translation was changed on weblate after the PR was opened, and it wasn't reflected in the PR?

@Natim any idea on how to fix the conflict?

**Pull request merged**
