### PR TITLE
#869 Fix Invitation Mail

### PR DESCRIPTION
**Pull request by anirudhgad**
This is my first contribution so I may have some minor errors but I think the functionality of the code should solve the Issue requested.
I used a google API call to create translation from english to any language without using manual templates by making edits to render_localized_.template function. Unfortunately the requirement of the issue to use jinja2 for automatic translation is not actually a functionality of jinja2 and will not work unless we have manual translations available which I feel defeats the purpose of the change.
Issue is that some times google translate may not be as grammatically correct as a manual translation.

### CODE REVIEW

**Comment by almet** [comment]
Hi, thanks for taking the time to do this work, however, as you say the "Issue is that some times google translate may not be as grammatically correct as a manual translation".

I believe we should do a manual translation instead. You can work on this if you want, it's described in #869

**Comment by almet** [comment]
Sorry, I feel this lacks some more explanations :-)

I don't think using google translation will solve this issue. We have people ready to volunteer some time in order to translate this project in different languages, so let's use this fantastic power :-)

I believe what we should do is use a `trans` block in the jinja template and then generate the translation files!

Let's continue the discussion in another pull-request if you still want to work on this :-)

**Comment by anirudhgad** [comment]
I initially tried using the trans block in the jinja template to generate them but scrapped it because I thought the requirement was for automation I will make some changes to it and upload again!

**Comment by almet** [comment]
Awesome, thanks !

**Pull request closed without merging**
