### PR TITLE
More responsive layout

### PR DESCRIPTION
**Pull request by Phyks**
This PR fixes the lack of responsive layout on mobile.

It should be ok on mobile devices for homepage and the main page of a given project, so that at least users could add new bills from a mobile device. Navbar on mobile device could still be enhanced though.

### CODE REVIEW

**Comment by almet** [comment]
Hi, and thanks for this! It will be helpful to a bunch of people, I'm sure :) I've reviewed and it seems to work like a charm. Let's merge !

**Comment by Phyks** [comment]
Thanks!

**Comment by JocelynDelalande** [comment]
@Phyks seems cool, thank you ! 

@almet should we close #113  ?

**Comment by Phyks** [comment]
My patch makes IHateMoney "responsive" in the sense that it should now be usable on mobile devices. I would not consider fully responsive though, especially since mobile UI is still very similar to desktop one and not particularly tailored for the mobile abilities. Not sure what was exactly wanting #113.

**Pull request merged**
