### PR TITLE
Statistics view #323

### LINKED ISSUE #323: Remove sidebar on statistics view
image

It seems to me totally redundant with the central table. What do you think ?

### PR DESCRIPTION
**Pull request by jyleong**
Updates:

Remove header and table column of 'Balance' in statistics view

Edited tests to reflect these changes

Fixes #323

### CODE REVIEW

**Comment by Glandos** [comment]
It seems to achieve the goal mentioned in #323.

However, I am still not sure it will increase readability in this overview.

**Comment by jyleong** [comment]
What if we moved the heading over to the side bar?
like:

Screen Shot 2019-12-22 at 2 08 45 PM

**Comment by almet** [comment]
@jyleong where are we with this? Should we merge it? Let us know!

**Comment by jyleong** [comment]
Yes we should thanks!

**Comment by Glandos** [comment]
I don't feel 100% sure about this, but I have nothing better in mind.

**Pull request merged**
